name: Upload Maven Package

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Deploy Maven Package
        run: |
          # GitHub hozzáférési token beállítása
          GITHUB_TOKEN="${{ secrets.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 }}"
          
          # Maven csomag build és feltöltése
          mvn clean package deploy -Dmaven.test.skip=true

          # Maven csomag feltöltése a GitHub Package Registry-be
          mvn deploy -Dregistry=https://maven.pkg.github.com/zoltan2561/Konyvtar -Dtoken=$GITHUB_TOKEN
