name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: mvn test --file pom.xml

      - name: Publish to GitHub Package Registry
        run: mvn deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
